title: Green Software Italia
email: green.software.italia@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Una community per parlare di come le decisioni tecnologiche 
  e aziendali influenzano il pianeta e la società.
github_username: Green-Software-Italia
search: true
locale: it_IT
atom_feed:
  hide: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: gsi_dark
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Green Software Italia"
  avatar : "/assets/images/GSI_logo.png"
  bio    : "Una community per parlare di come le decisioni tecnologiche e aziendali influenzano il pianeta e la società."
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/green-software-italia"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Green-Software-Italia"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:green.software.italia@gmail.com"

footer:
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/green-software-italia"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Green-Software-Italia"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:green.software.italia@gmail.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
